[package]
name = "vault_moukaeritai_work"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
regex = "1.12.3"
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "1.0"

[dev-dependencies]
argon2 = "0.5.3"
hex = "0.4.3"
aes-gcm = "0.10.3"
tempfile = "3.27.0"
